version: "3.5"
services:
  nginx:
    image: nginx:1.17.7-alpine
    volumes:
      - ./nginx-dev.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 3000:80
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app
  backend:
    build:
      context: backend
      dockerfile: Dockerfile.dev
    ports:
      - 8000:8000
    volumes:
      - ./backend:/app
  db:
    image: postgres
    restart: always
    environment:
          POSTGRES_PASSWORD: "postgres"
          POSTGRES_USER: "postgres"
          POSTGRES_DB: "postgres"

