version: "3.5"
services:
  nginx:
    image: nginx:1.17.7-alpine
    volumes:
      - ./nginx-dev.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 3000:80
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app
  backend:
    build:
      context: backend
      dockerfile: Dockerfile.dev
    ports:
      - 5000:5000
    volumes:
      - ./backend:/app
